### ISSUE TITLE
Please do not call this micropython-requests

### ISSUE THREAD

**Issue by sigmavirus24** [balloob/micropython-http-client#1]
This does not seem to implement proper TLS verification. `ussl.wrap_socket` does not verify the connection so a user could easily be attacked via a man-in-the-middle attack since they won't need to work at faking out a certificate of any sort. Part of requests is the API, certainly, but the larger part is the security. You're effectively promising the latter without delivering it by using the name.

**Comment by ncoghlan** [comment]
+1

"Use requests instead" is a frequent response to folks concerned about the fact that older versions of the Python standard library's SSL module don't verify certificates by default, so providing the requests API under the same name without providing the same security guarantees is problematic.

**Comment by balloob** [comment]
Sure, I'll rename it.

**Comment by ncoghlan** [comment]
Thanks for the quick response!

In terms of actually creating secure SSL/TLS connections, ussl.wrap_socket *does* support passing certificate information (as long as those certificates have been uploaded to the device), so it may be desirable to make that configurable through the abstraction layer: http://docs.micropython.org/en/latest/library/ussl.html

**Comment by ncoghlan** [comment]
I dug a bit further into the implementation of ussl.wrap_socket, and it currently skips certificate validation even if you provide the necessary configuration settings. Since the code here was inspired by that in MicroPython's upip, I filed an issue there: https://github.com/micropython/micropython-lib/issues/69
